[project]
name = "price-comparison-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
]

[tool.uv]
dev-dependencies = [
    "ipython>=8.29.0",
]
